### ISSUE TITLE
Error when downloading

### ISSUE THREAD

**Issue by Mosk0ng** [matrix1001/glibc-all-in-one#2]
I got this when downloading. I reckon that the source may not has this glibcxx.deb. The list maybe wrong

Getting 2.29-0ubuntu2_amd64
  -> Location: https://mirror.tuna.tsinghua.edu.cn/ubuntu/pool/main/g/glibc/libc6_2.29-0ubuntu2_amd64.deb
  -> Downloading libc binary package
Failed to download package from https://mirror.tuna.tsinghua.edu.cn/ubuntu/pool/main/g/glibc/libc6_2.29-0ubuntu2_amd64.deb

**Comment by matrix1001** [comment]
Somehow removed by the source. I will check it.

**Comment by matrix1001** [comment]
> I got this when downloading. I reckon that the source may not has this glibcxx.deb. The list maybe wrong
> 
> Getting 2.29-0ubuntu2_amd64
> -> Location: https://mirror.tuna.tsinghua.edu.cn/ubuntu/pool/main/g/glibc/libc6_2.29-0ubuntu2_amd64.deb
> -> Downloading libc binary package
> Failed to download package from https://mirror.tuna.tsinghua.edu.cn/ubuntu/pool/main/g/glibc/libc6_2.29-0ubuntu2_amd64.deb

The sorce added glibc2.30 and glibc2.31,  but removed glibc2.29.
I will fix it later.
